/**
 * Writes a migration for whatever changed in the entity metadata since the last
 * one.
 *
 *     __pmRun__ db:migration -- add-invoice-notes
 *     __pmRun__ db:migration -- add-invoice-notes --dialect mysql
 *
 * It compares the model against `migrations/.snapshot.json` — committed, and
 * deliberately not the live database. Reading the database would mean a
 * migration that cannot be written without a connection to an environment, and
 * one that came out differently depending on which environment you happened to
 * be pointed at. The snapshot is what the code said, which is the same for
 * everybody who has the code.
 *
 * **Nothing is applied.** The file is plain SQL for umzug, node-pg-migrate,
 * Flyway or `psql < file`, whatever this project already uses. Owning a runner
 * would mean owning an applied-migrations table, locking, ordering and rollback,
 * and a toolkit you adopt one package at a time should not make you switch
 * migration tools to use its entity mapping.
 *
 * **When nothing changed it writes nothing at all**, on purpose: a tool that
 * emits an empty file every run teaches people to stop reading its output, and
 * then the one that mattered goes out unread.
 */
import fs from "node:fs";
import path from "node:path";
import { parseArgs } from "node:util";

import { ddlDialectFor, diffSnapshots, emptySnapshot, snapshotOf } from "monolite-data";
import type { SchemaSnapshot } from "monolite-data";
import { entitiesOf } from "monolite-di";

import { MODULES } from "../composition/modules";

const MIGRATIONS = path.resolve("migrations");
const SNAPSHOT = path.join(MIGRATIONS, ".snapshot.json");

const { values, positionals } = parseArgs({
  options: { dialect: { type: "string" } },
  allowPositionals: true,
});

const [name] = positionals;

if (!name) {
  console.error("usage: __pmRun__ db:migration -- <name> [--dialect <engine>]");
  console.error("the name goes in the file name, so make it say what the change is");
  process.exit(1);
}

const engine = values.dialect ?? process.env.DATA_SOURCE ?? "__dataSource__";
const dialect = ddlDialectFor(engine);

if (!dialect) {
  console.error(`There are no migrations to write for "${engine}": it has no schema.`);
  process.exit(1);
}

const entities = entitiesOf(MODULES).map((registration) => registration.metadata);
const previous = readSnapshot();
const next = snapshotOf(entities);
const statements = diffSnapshots(previous, next, dialect, { entities });

if (statements.length === 0) {
  console.log("The model matches the last snapshot. No migration written.");
  process.exit(0);
}

const stamp = timestamp();
const file = path.join(MIGRATIONS, `${stamp}-${slug(name)}.sql`);

const header = [
  `-- ${stamp} ${name}`,
  `-- Generated by monolite from the entity metadata, for ${dialect.name}.`,
  "--",
  "-- Read it before applying it. Lines that are commented out destroy data:",
  "-- they are yours to decide on, which is why they are not runnable as written.",
  "",
].join("\n");

fs.mkdirSync(MIGRATIONS, { recursive: true });
fs.writeFileSync(file, `${header}${statements.join("\n")}\n`, "utf8");

// The snapshot moves only once the migration exists, so a run interrupted
// between the two leaves the change still pending rather than silently skipped.
fs.writeFileSync(SNAPSHOT, `${JSON.stringify(next, null, 2)}\n`, "utf8");

console.log(`${statements.length} statement(s) -> migrations/${path.basename(file)}`);
console.log("Apply it with whatever this project already uses; nothing was run.");

/** The previous model, or an empty one the first time. */
function readSnapshot(): SchemaSnapshot {
  if (!fs.existsSync(SNAPSHOT)) return emptySnapshot();

  const stored = JSON.parse(fs.readFileSync(SNAPSHOT, "utf8")) as SchemaSnapshot;

  if (stored.version !== 1) {
    // Loudly, rather than diffing against a shape this version does not
    // understand and emitting a migration that looks plausible.
    console.error(`migrations/.snapshot.json is version ${stored.version}; this tool reads 1.`);
    process.exit(1);
  }

  return stored;
}

/** `20260822T174530`: sorts as a string, which is how migrations are ordered. */
function timestamp(): string {
  return new Date().toISOString().replace(/[-:]/g, "").replace(/\.\d+Z$/, "");
}

function slug(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}
