import {
  ddlDialectFor,
  defineEntity,
  diffSnapshots,
  emitSchema,
  emitTable,
  emptySnapshot,
  EntitySchema,
  mysqlDdl,
  oracleDdl,
  postgresDdl,
  snapshotOf,
  sqlServerDdl,
  type AnyEntityMetadata,
} from "monolite-data";

interface ICategory {
  pkCategory: number;
  name: string;
}

interface IProduct {
  pkProduct: number;
  categoryId: number;
  sku: string;
  name: string;
  notes: string | null;
  priceCents: number;
  available: boolean;
  createdAt: Date;
}

const CATEGORY = defineEntity<ICategory>({
  table: "CATEGORIES",
  primaryKey: "pkCategory",
  identity: true,
  columns: {
    pkCategory: { name: "PK_CATEGORY", kind: "number", insertable: false, updatable: false },
    name: { name: "NAME", kind: "string", length: 80, nullable: false, unique: true },
  },
});

const PRODUCT = defineEntity<IProduct>({
  table: "PRODUCTS",
  primaryKey: "pkProduct",
  identity: true,
  columns: {
    pkProduct: { name: "PK_PRODUCT", kind: "number", insertable: false, updatable: false },
    categoryId: { name: "FK_CATEGORY", kind: "number", nullable: false },
    sku: { name: "SKU", kind: "string", length: 32, nullable: false, unique: true },
    name: { name: "NAME", kind: "string", length: 150, nullable: false },
    notes: { name: "NOTES", kind: "string", length: "max" },
    priceCents: { name: "PRICE_CENTS", kind: "number", nullable: false, default: "0" },
    available: { name: "AVAILABLE", kind: "boolean", nullable: false, default: "1" },
    createdAt: { name: "CREATED_AT", kind: "date", updatable: false },
  },
  relations: {
    category: { to: "CATEGORIES", localKey: "categoryId", foreignKey: "pkCategory" },
  },
  indexes: [{ columns: ["categoryId", "name"] }],
});

const ENTITIES: AnyEntityMetadata[] = [CATEGORY, PRODUCT];

describe("emitTable", () => {
  it("declares every mapped column, the primary key and its generated id", () => {
    const { create } = emitTable(PRODUCT, postgresDdl);

    expect(create).toContain("CREATE TABLE PRODUCTS (");
    expect(create).toContain("PK_PRODUCT INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL");
    expect(create).toContain("CONSTRAINT PK_PRODUCTS PRIMARY KEY (PK_PRODUCT)");
  });

  /**
   * The disagreement this generator exists to end.
   *
   * The mapping writes a boolean as `1` and `0` — see
   * `EntitySchema.toColumnValue` — and PostgreSQL's `BOOLEAN` will not take an
   * integer. A demo lost an afternoon to a hand-written `BOOLEAN` column
   * rejecting every insert the repository made. Emitting the schema from the
   * same metadata the repository reads is what makes that impossible.
   */
  it("types a boolean as the integer the mapping actually writes", () => {
    expect(emitTable(PRODUCT, postgresDdl).create).toContain("AVAILABLE SMALLINT");
    expect(emitTable(PRODUCT, sqlServerDdl).create).toContain("AVAILABLE SMALLINT");
    expect(emitTable(PRODUCT, oracleDdl).create).toContain("AVAILABLE NUMBER(1)");
    expect(emitTable(PRODUCT, mysqlDdl).create).toContain("AVAILABLE TINYINT(1)");
  });

  it("gives a string its declared width, and the unbounded type for max", () => {
    const postgres = emitTable(PRODUCT, postgresDdl).create;

    expect(postgres).toContain("SKU VARCHAR(32)");
    expect(postgres).toContain("NOTES TEXT");
    expect(emitTable(PRODUCT, sqlServerDdl).create).toContain("NOTES NVARCHAR(MAX)");
    expect(emitTable(PRODUCT, oracleDdl).create).toContain("SKU VARCHAR2(32 CHAR)");
  });

  it("defaults a string with no width to 255 rather than refusing to emit", () => {
    const loose = defineEntity<{ pk: number; label: string }>({
      table: "LOOSE",
      primaryKey: "pk",
      columns: { pk: { name: "PK", kind: "number" }, label: "LABEL" },
    });

    expect(emitTable(loose, postgresDdl).create).toContain("LABEL VARCHAR(255)");
  });

  it("makes a column NOT NULL only when the model says so, and the key always", () => {
    const create = emitTable(PRODUCT, postgresDdl).create;

    expect(create).toContain("SKU VARCHAR(32) NOT NULL");
    // Not declared either way, so it stays nullable: the permissive default is
    // the only one that cannot break a table that already exists.
    expect(create).toContain("CREATED_AT TIMESTAMPTZ,");
    expect(create).toContain("NOTES TEXT,");
  });

  it("emits a default verbatim, before the nullability", () => {
    expect(emitTable(PRODUCT, postgresDdl).create).toContain("PRICE_CENTS INTEGER DEFAULT 0 NOT NULL");
  });

  it("turns a unique column into a named constraint", () => {
    expect(emitTable(PRODUCT, postgresDdl).create).toContain(
      "CONSTRAINT UQ_PRODUCTS_SKU UNIQUE (SKU)"
    );
  });

  it("writes an index over the columns, in the order they were declared", () => {
    const [index] = emitTable(PRODUCT, postgresDdl).indexes;

    expect(index).toBe("CREATE INDEX IX_PRODUCTS_CATEGORYID_NAME ON PRODUCTS (FK_CATEGORY, NAME);");
  });

  it("keeps a generated constraint name inside the shortest engine limit", () => {
    const long = defineEntity<{ pk: number; value: string }>({
      table: "A_TABLE_WITH_A_QUITE_UNREASONABLY_LONG_NAME_FOR_TESTING_LIMITS",
      primaryKey: "pk",
      columns: {
        pk: { name: "PK", kind: "number" },
        value: { name: "A_COLUMN_WITH_ITS_OWN_VERY_LONG_NAME", kind: "string", unique: true },
      },
    });

    const names = [...emitTable(long, postgresDdl).create.matchAll(/CONSTRAINT (\S+)/g)];

    expect(names.length).toBeGreaterThan(0);
    for (const [, name] of names) expect(name.length).toBeLessThanOrEqual(63);
  });
});

describe("emitSchema", () => {
  it("creates every table before constraining any of them", () => {
    const script = emitSchema(ENTITIES, postgresDdl);

    const lastCreate = script.lastIndexOf("CREATE TABLE");
    const firstAlter = script.indexOf("ALTER TABLE");

    // Not tidiness: a foreign key can point at a table declared later, and two
    // tables that point at each other have no valid ordering at all.
    expect(firstAlter).toBeGreaterThan(lastCreate);
  });

  it("resolves the referenced column through the other entity's mapping", () => {
    const script = emitSchema(ENTITIES, postgresDdl);

    // The relation says `foreignKey: "pkCategory"`, which is the property. The
    // column is `PK_CATEGORY`, and only the other entity's mapping knows that.
    expect(script).toContain(
      "ALTER TABLE PRODUCTS ADD CONSTRAINT FK_PRODUCTS_FK_CATEGORY " +
        "FOREIGN KEY (FK_CATEGORY) REFERENCES CATEGORIES (PK_CATEGORY) ON DELETE RESTRICT;"
    );
  });

  it("names the entity that is missing when a relation points nowhere", () => {
    expect(() => emitSchema([PRODUCT], postgresDdl)).toThrow(/CATEGORIES/);
  });

  it("uses IF NOT EXISTS where the engine has it, and says so where it does not", () => {
    expect(emitSchema(ENTITIES, postgresDdl, { ifNotExists: true })).toContain(
      "CREATE TABLE IF NOT EXISTS CATEGORIES"
    );

    const oracle = emitSchema(ENTITIES, oracleDdl, { ifNotExists: true });

    expect(oracle).not.toContain("IF NOT EXISTS");
    expect(oracle).toContain("has no such clause");
  });
});

describe("ddlDialectFor", () => {
  it("takes the names DATA_SOURCE uses, including the aliases", () => {
    expect(ddlDialectFor("postgres")).toBe(postgresDdl);
    expect(ddlDialectFor("postgresql")).toBe(postgresDdl);
    expect(ddlDialectFor("SQLSERVER")).toBe(sqlServerDdl);
    expect(ddlDialectFor("mariadb")).toBe(mysqlDdl);
  });

  /**
   * Absent rather than present-and-throwing. Neither engine has DDL, and a
   * caller should learn that from a lookup that fails, not from a statement
   * that turns out to be a lie when something tries to run it.
   */
  it("answers null for the engines that have no schema to emit", () => {
    expect(ddlDialectFor("memory")).toBeNull();
    expect(ddlDialectFor("mongodb")).toBeNull();
  });
});

describe("snapshotOf and diffSnapshots", () => {
  const options = { entities: ENTITIES };

  it("emits nothing at all when nothing changed", () => {
    const snapshot = snapshotOf(ENTITIES);

    // A migration tool that writes an empty file every run teaches people to
    // stop reading its output, and the next one that matters goes out unread.
    expect(diffSnapshots(snapshot, snapshot, postgresDdl, options)).toEqual([]);
  });

  it("creates the whole schema from nothing", () => {
    const statements = diffSnapshots(emptySnapshot(), snapshotOf(ENTITIES), postgresDdl, options);

    expect(statements.some((one) => one.startsWith("CREATE TABLE CATEGORIES"))).toBe(true);
    expect(statements.some((one) => one.startsWith("CREATE TABLE PRODUCTS"))).toBe(true);
  });

  it("adds a column that appeared", () => {
    const before = snapshotOf(ENTITIES);
    const after = snapshotOf([
      CATEGORY,
      {
        ...PRODUCT,
        columns: { ...PRODUCT.columns, weightGrams: { name: "WEIGHT_G", kind: "number" } },
      } as AnyEntityMetadata,
    ]);

    const statements = diffSnapshots(before, after, postgresDdl, options);

    expect(statements).toContain("ALTER TABLE PRODUCTS ADD WEIGHT_G INTEGER;");
  });

  /**
   * `NOT NULL` on a table that already has rows fails, so the column goes in
   * nullable and the tightening is left as a commented statement after the
   * backfill. A migration that cannot run on a populated database is not one.
   */
  it("adds a NOT NULL column nullable, and says what is left to do", () => {
    const before = snapshotOf(ENTITIES);
    const after = snapshotOf([
      CATEGORY,
      {
        ...PRODUCT,
        columns: {
          ...PRODUCT.columns,
          slug: { name: "SLUG", kind: "string", length: 60, nullable: false },
        },
      } as AnyEntityMetadata,
    ]);

    const statements = diffSnapshots(before, after, postgresDdl, options);

    expect(statements).toContain("ALTER TABLE PRODUCTS ADD SLUG VARCHAR(60);");
    expect(statements.join("\n")).toContain("Backfill it");
    expect(statements.join("\n")).toContain("SET NOT NULL");
  });

  it("comments out a drop instead of emitting it", () => {
    const before = snapshotOf(ENTITIES);
    const after = snapshotOf([
      CATEGORY,
      { ...PRODUCT, columns: withoutNotes(PRODUCT.columns) } as AnyEntityMetadata,
    ]);

    const statements = diffSnapshots(before, after, postgresDdl, options);
    const script = statements.join("\n");

    expect(script).toContain("-- ALTER TABLE PRODUCTS DROP COLUMN NOTES;");
    // Everything else this tool writes is additive or reversible. This one
    // destroys data, and a generated file that runs is one somebody runs.
    expect(statements.some((one) => one.startsWith("ALTER TABLE PRODUCTS DROP"))).toBe(false);
  });

  it("says out loud that it cannot tell a rename from a drop and an add", () => {
    const renamed = {
      ...PRODUCT,
      columns: {
        ...withoutNotes(PRODUCT.columns),
        notes: { name: "REMARKS", kind: "string", length: "max" },
      },
    } as AnyEntityMetadata;

    const script = diffSnapshots(
      snapshotOf(ENTITIES),
      snapshotOf([CATEGORY, renamed]),
      postgresDdl,
      options
    ).join("\n");

    expect(script).toContain("RENAME COLUMN");
    expect(script).toContain("ALTER TABLE PRODUCTS ADD REMARKS TEXT;");
    expect(script).toContain("-- ALTER TABLE PRODUCTS DROP COLUMN NOTES;");
  });

  it("reports a widened column with what it was and what it became", () => {
    const wider = {
      ...PRODUCT,
      columns: { ...PRODUCT.columns, sku: { name: "SKU", kind: "string", length: 64, nullable: false, unique: true } },
    } as AnyEntityMetadata;

    const script = diffSnapshots(
      snapshotOf(ENTITIES),
      snapshotOf([CATEGORY, wider]),
      postgresDdl,
      options
    ).join("\n");

    expect(script).toContain("-- PRODUCTS.SKU: string(32) not null -> string(64) not null");
    expect(script).toContain("ALTER TABLE PRODUCTS ALTER COLUMN SKU TYPE VARCHAR(64);");
  });

  /**
   * A property renamed while its column stays put is a refactor of the code,
   * not of the database, and it has to produce no migration at all. That is why
   * a snapshot is keyed by column and never by property.
   */
  it("ignores a property renamed over the same column", () => {
    const renamedProperty = {
      ...PRODUCT,
      primaryKey: "pkProduct",
      columns: { ...withoutNotes(PRODUCT.columns), remarks: { name: "NOTES", kind: "string", length: "max" } },
    } as AnyEntityMetadata;

    expect(
      diffSnapshots(snapshotOf(ENTITIES), snapshotOf([CATEGORY, renamedProperty]), postgresDdl, options)
    ).toEqual([]);
  });

  it("survives a round trip through JSON, which is how it is stored", () => {
    const snapshot = snapshotOf(ENTITIES);
    const reloaded = JSON.parse(JSON.stringify(snapshot)) as typeof snapshot;

    expect(diffSnapshots(reloaded, snapshot, postgresDdl, options)).toEqual([]);
  });
});

/** The product columns without `notes`, for the drop and the rename cases. */
function withoutNotes(columns: (typeof PRODUCT)["columns"]) {
  const rest = { ...columns } as Record<string, unknown>;
  delete rest.notes;
  return rest as Omit<(typeof PRODUCT)["columns"], "notes">;
}

/**
 * The DDL and the SQL the repository generates, checked against each other.
 *
 * The real round trip is to run the emitted script on an engine and then drive
 * the tables with the repository — done against PostgreSQL 16 while this was
 * written, and not shipped here because CI has no database and adding a driver
 * to the monorepo for a test that never runs in it buys nothing.
 *
 * What *can* run everywhere is the half that catches the same failure: every
 * identifier the repository puts in a statement must be declared by the DDL. If
 * the two ever drift — a column the mapping renames, a table the emitter
 * spells differently — this fails without anything having to be installed.
 */
describe("the emitted schema and the generated SQL", () => {
  it("declare and name the same columns", () => {
    const { create } = emitTable(PRODUCT, postgresDdl);
    const declared = new Set(
      [...create.matchAll(/^ {2}([A-Z_][A-Z0-9_]*) /gm)].map(([, column]) => column)
    );

    // Everything the repository can put in a SELECT, an INSERT or a WHERE.
    const schema = new EntitySchema(PRODUCT);
    const used = schema.properties.map((property) => schema.columnOf(property));

    expect(used.length).toBeGreaterThan(0);
    for (const column of used) expect(declared.has(column)).toBe(true);
  });

  it("agree on the table name, which is what a statement opens with", () => {
    const schema = new EntitySchema(PRODUCT);

    expect(emitTable(PRODUCT, postgresDdl).create).toContain(`CREATE TABLE ${schema.table} (`);
  });

  /**
   * The soft-delete column has to exist and has to hold the values the mapping
   * compares against — `1` and `0`. A `BOOLEAN` column would satisfy the first
   * and fail the second on every read, which is precisely the failure that
   * generating the schema is meant to make impossible.
   */
  it("give the soft-delete flag a type that holds the values the filter compares", () => {
    const soft = defineEntity<{ pk: number; active: boolean }>({
      table: "SOFT",
      primaryKey: "pk",
      columns: {
        pk: { name: "PK", kind: "number" },
        active: { name: "ACTIVE", kind: "boolean" },
      },
      softDelete: { property: "active", activeValue: 1, deletedValue: 0 },
    });

    for (const dialect of [postgresDdl, sqlServerDdl, mysqlDdl, oracleDdl]) {
      const line = emitTable(soft, dialect).create.match(/ {2}ACTIVE (.+?)[,\n]/)?.[1] ?? "";

      expect(line).not.toMatch(/BOOL/i);
      expect(line).toMatch(/INT|NUMBER/i);
    }
  });
});
